theme: jekyll-theme-minimal
locale                   : "en-US"
title                    : "Paul Zivich"
title_separator          : "-"
name                     : &name "Paul Zivich"
url                      : https://pzivich.github.io

author:
  name             : "Paul Zivich"
  avatar           : "/images/paul_zivich_min.JPG"
  bio              : "Paul Zivich is a postdoctoral researcher at UNC-CH"
  location         : "Chapel Hill, NC"
  pubmed           : "https://pubmed.ncbi.nlm.nih.gov/?term=Paul+Zivich"
  googlescholar    : "https://scholar.google.com/citations?user=hbU-gZ0AAAAJ&hl=en"
  email            : "zivich.5@gmail.com"
  researchgate     : "https://www.researchgate.net/profile/Paul-Zivich"
  github           : "pzivich"
  orcid            : "https://orcid.org/0000-0002-9932-1095"
  stackoverflow    : "https://stats.stackexchange.com/users/247479/pzivich"
  twitter          : "PausalZ"
